version: v0.1
testName: trips-loadtest
testPlan: loadtest-trips-api.jmx
description: 'Hitting azure function to perform a loadtest'
engineInstances: 1
failureCriteria: 
- avg(response_time_ms) > 25
- percentage(error) > 20