name: Build and Deploy Distributed Tracing

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'flights-generator-api'
  LOADTEST_ROOT: './loadtest'
  FLIGHTS_ROOT: './application'
  FLIGHTS_PACKAGE: './application/dist/'
jobs:
  build_flights:
    defaults:
      run:
        working-directory: ${{ env.FLIGHTS_ROOT }}
    name: build application
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        python setup.py bdist_wheel 
    - uses: actions/upload-artifact@v2
      with:
        name: flights-api
        path: ${{ env.FLIGHTS_PACKAGE }}
  unit_test:
    name: Run unit tests 
    needs: [build_flights]
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - uses: actions/download-artifact@v2
      with:
        name: flights-api
        path: ${{ env.FLIGHTS_ROOT }}/dist
    - name: Install dependencies
      run: |
        ls .
        ls ${{env.FLIGHTS_ROOT}}/dist
        python -m pip install --upgrade pip
        pip install ${{env.FLIGHTS_ROOT}}/dist/*
    - name: run tests
      working-directory: ${{env.FLIGHTS_ROOT}} 
      run: |
        python -m pytest .

  
  deploy_flight:
    name: Deploy flights
    needs: [unit_test] 
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: actions/download-artifact@v2
      with:
        name: flights-api
        path: ${{ env.FLIGHTS_ROOT }}
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package:  ${{ env.FLIGHTS_ROOT }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
  loadtest:
    name: Load test on staging environment
    needs: [deploy_flight] 
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Azure Load Testing'
      working-directory: ${{env.LOADTEST_ROOT}} 
      uses: azure/load-testing@v1
      with:
        loadTestConfigFile: 'config.yaml'
        loadTestResource: csu-sr-loadtest-service
        resourceGroup: csu-nl-sr-loadtest-with-cicd
    - uses: actions/upload-artifact@v2
      with:
        name: loadTestResults
        path: ${{ github.workspace }}/gloadTest
